version: '3.3'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: ./Dockerfile
    user: root
    ports:
      - '8111:8080'
      - '50000:50000'
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  youtrack:
    image: jetbrains/youtrack:2018.4.49352
    ports:
      - '8080:8080'
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: 'vsoshyn'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - 5432:5432
  portainer:
    image: portainer/portainer
    ports:
      - '9000:9000'
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2.6
    ports:
      - '5000:5000'
volumes:
  jenkins-data: