version: "3.3"
services:
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: 'task-manager'
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - task-management-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
  task-manager:
    build: ../../backend
#    command: sh -c './wait-for.sh postgres:5432 -t 5'
    depends_on:
      - postgres
volumes:
  task-management-postgres: